
(defun sweyla708980 ()
  "Theme generated by Sweyla: http://themes.sweyla.com/seed/708980/"
  (interactive)
  (color-theme-install
   '(sweyla708980
     ((background-color . "#040000")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#37CA22"))))
     (font-lock-constant-face ((t (:foreground "#A00074"))))
     (font-lock-builtin-face ((t (:foreground "#3F3F9D"))))
     (font-lock-function-name-face ((t (:foreground "#147B5A"))))
     (font-lock-variable-name-face ((t (:foreground "#A733D3"))))
     (font-lock-keyword-face ((t (:foreground "#2B6070"))))
     (font-lock-string-face ((t (:foreground "#9D0C3D"))))
     (font-lock-doc-string-face ((t (:foreground "#9D0C3D"))))
     (font-lock-type-face ((t (:foreground "#0C49A9"))))
     )))

(provide 'sweyla708980)
